# if normally you called
  some_cmd ...its args...
  # or
  path/to/some_script.py ...its args...
  # or
  python3 path/to/some_script.py ...its args...
  # or
  python3 -m some_module ...its args...


# then your calls become:
  # command known to be a script (e.g. 'pip') and it's args
  traceback-with-varaibles some_cmd ...its args...
  
  # script and it's args
  traceback-with-varaibles path/to/some_script.py ...its args...

  # a module (e.g. 'http.server') and it's args
  traceback-with-varaibles some_module ...its args...


# help:
  traceback-with-variables --help


# more
  # customizing tracebacks
  traceback-with-varaibles --max-value-str-len 100 --num-context-lines 3 path/to/some_script.py ...its args...
  
  # synthwave+
  traceback_with_variables --color-scheme synthwave ...
  traceback_with_variables --color-scheme nice ...
  
  # runnig with `python -m`
  python3 -m traceback_with_variables path/to/some_script.py ...its args...

